[package]
name = "exfetch"
version = "0.11.0"
edition = "2024"

[target.'cfg(target_os = "linux")'.dependencies]
sysinfo_dot_h = "0.2.1"

[target.'cfg(android)'.dependencies]
sysinfo_dot_h = "0.2.1"

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
panic = "abort"
strip = true
